In [1]:
import pandas as pd

In [10]:
df = pd.read_csv('../predictions/gene_scores/gene_scores_Adipocytes_Brown.csv')

In [16]:
df.sort_values('Score', ascending=False).head(20)

      Unnamed: 0                Gene     Score
1236        1236  ENSRNOG00000062930  5.688358
1469        1469  ENSRNOG00000068039  3.814671
1183        1183                 Dst  2.415979
4875        4875                 Vcl  2.082000
842          842               Clic4  1.838358
1621        1621               Eepd1  1.651003
2260        2260              Igfbp7  1.607422
1154        1154               Dock9  1.551066
2730        2730               Lamc1  1.507149
532          532               Cald1  1.475688
1716        1716                Etv6  1.445182
971          971               Csrp1  1.424213
3603        3603                Pls3  1.415491
4792        4792               Tshz2  1.394468
3074        3074              Mt-co2  1.381139
898          898              Col4a1  1.345842
414          414               Bcl6b  1.338354
3107        3107                Myh9  1.275335
3274        3274               Nrxn1  1.251223
1605        1605                Ebf1  1.224382

In [19]:
df[df['Gene'].str.startswith('Nr')]

      Unnamed: 0   Gene     Score
3260        3260  Nr2f1  0.033267
3261        3261  Nr2f2  0.020956
3262        3262  Nr4a1 -0.283018
3263        3263  Nr4a3  0.010177
3264        3264  Nr5a2  0.187924
3265        3265   Nrap  0.007645
3266        3266  Nrarp  0.101077
3267        3267   Nrep  0.332054
3268        3268   Nrg1 -0.026874
3269        3269   Nrg3 -0.024385
3270        3270    Nrk  0.009535
3271        3271   Nrn1 -0.021043
3272        3272  Nrros  0.868772
3273        3273  Nrsn1 -0.010776
3274        3274  Nrxn1  1.251223
3275        3275  Nrxn2 -0.020519
3276        3276  Nrxn3  0.011957