In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../predictions/gene_scores/gene_scores_Adipocytes_3.csv')

In [6]:
df.sort_values('Score', ascending=False).head(30)

      Unnamed: 0                Gene     Score
1236        1236  ENSRNOG00000062930  2.485635
1469        1469  ENSRNOG00000068039  1.799109
4556        4556                Tcf4  1.327532
1709        1709                Etl4  1.310011
4792        4792               Tshz2  1.169850
1605        1605                Ebf1  1.146648
709          709               Cdh13  1.140187
1927        1927             Galnt18  1.101151
2898        2898               Magi1  1.071436
1049        1049               Dach1  1.066678
3544        3544             Pitpnc1  1.059064
1152        1152               Dock4  1.038421
91            91              Ablim3  1.026398
3571        3571               Plcb4  1.016635
145          145             Adamts9  1.013296
2369        2369               Itpkb  1.004631
1154        1154               Dock9  0.993346
2618        2618        LOC108352070  0.987380
301          301            Arhgap31  0.971230
4463        4463               Stox2  0.915702
2429        2429                 Kdr  0.906107
606          606             Ccdc85a  0.879114
1850        1850                Fli1  0.875801
1621        1621               Eepd1  0.875446
1842        1842               Fhod3  0.863140
2906        2906               Maml2  0.846839
296          296            Arhgap18  0.844902
3732        3732               Ptprg  0.826742
2260        2260              Igfbp7  0.811313
2352        2352               Itga6  0.807398

In [5]:
df[df['Gene'].str.startswith('Eb')]

      Unnamed: 0  Gene     Score
1605        1605  Ebf1  1.146648
1606        1606  Ebf2  0.245972
1607        1607  Ebf4 -0.033545