In [1]:
import pandas as pd

In [2]:
df_ECs_Cap = pd.read_csv('../predictions/gene_scores/gene_scores_ECs_Cap.csv')

In [7]:
df.sort_values('Score', ascending=False).head(30)

      Unnamed: 0     Gene     Score
4475        4475    Sulf1  6.582903
1656        1656      Eln  5.659719
914          914   Col8a1  4.168641
4148        4148   Setbp1  4.014178
3733        3733    Ptprj  3.906035
3237        3237   Nos1ap  3.691771
3551        3551  Pkhd1l1  3.587488
2168        2168    Hmcn1  3.356518
2353        2353    Itga9  3.310483
4877        4877    Vegfc  3.205135
3178        3178     Nebl  3.199856
4299        4299   Slc8a1  3.169366
1102        1102     Dgkb  2.992185
3597        3597    Plpp1  2.883589
3450        3450    Pcdh7  2.872793
3130        3130     Myof  2.841507
4375        4375   Specc1  2.692998
1118        1118     Dkk2  2.672393
2746        2746     Ldb2  2.657190
4279        4279   Slc4a4  2.648322
1645        1645     Ehd4  2.570005
1794        1794     Fbn1  2.512322
3702        3702   Prune2  2.500440
1677        1677   Entpd1  2.381433
373          373   Atp8b1  2.356742
4606        4606   Thsd7a  2.283212
1813        1813   Fchsd2  2.282046
3292        3292    Nuak1  2.215251
1654        1654    Elmo1  2.156707
3286        3286     Ntn1  2.115610

In [6]:
df[df['Gene'].str.startswith('Eb')]

      Unnamed: 0  Gene     Score
1605        1605  Ebf1 -3.011454
1606        1606  Ebf2  1.842746
1607        1607  Ebf4 -0.107512